[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello"
path = "src/main.rs"

[dependencies]

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true

[profile.dev]
panic = "abort"
